### ISSUE TITLE
Wrong birthplace code error (missing date-range in the data-source).

### ISSUE THREAD

**Issue by ncorona** [fabiocaccamo/python-codicefiscale#113] opened 2023-08-21 19:36 UTC
**Python version**
3.9

**Package version**
0.6.1

**Current behavior (bug description)**
Hi! I got this error when decoding a valid codicefiscale value.

_Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/codicefiscale/codicefiscale.py", line 440, in decode
    raise ValueError(f"[codicefiscale] wrong birthplace code: '{birthplace_code}'")
ValueError: [codicefiscale] wrong birthplace code: 'G133'_

I think some entry is missing in the municipalities.json file,  in particular for the range from 1928-11-27 to 1948-05-07.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-codicefiscale/issues/113">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/113/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/113/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment] 2023-08-21 20:38
@ncorona thank you for reporting this. 

Actually data is taken from https://www.anagrafenazionale.interno.it as it is probably the most reliable data-source, do you know a better alternative?

**Comment by ncorona** [comment] 2023-08-28 18:42
@fabiocaccamo  thank you for your fast reply!
This is exactly what I was talking about, apparently the municipality is not associated with any code in that time frame. I checked the sources you pointed out to me and apparently there is missing data at the source (ISTAT)...
And unfortunately G133 is not the only municipality with this problem :\
I was looking for other sources to be able to cross/integrate the data but I didn't find anything suitable :(
I can't share the codes here for obvious privacy reasons but they are valid tax codes belonging to real people with valid

**Comment by fabiocaccamo** [comment] 2023-08-28 19:42
@ncorona yes, the problem is that unfortunately there is not a perfect data source.

**Comment by ncorona** [comment] 2023-08-28 19:59
Birth date falls in the missing range. Here some of the errors, with anonymized codes:
[codicefiscale] wrong birthplace code: 'G133' / birthdate: '1939-04-04T00:00:00'. _XXXXXX_39D44G133_X_
[codicefiscale] wrong birthplace code: 'F383' / birthdate: '1946-04-11T00:00:00'. _XXXXXX_46D11F383_X_
[codicefiscale] wrong birthplace code: 'F383' / birthdate: '1950-06-18T00:00:00'._XXXXXX_50H18F383_X_
[codicefiscale] wrong birthplace code: 'L513' / birthdate: '1938-03-31T00:00:00'. _XXXXXX_38C71L513_X_
[codicefiscale] wrong birthplace code: 'G133' / birthdate: '1943-03-14T00:00:00'. _XXXXXX_43C14G133_X_

**Comment by fabiocaccamo** [comment] 2023-08-28 20:03
Ok, it's pretty obvious that a whole date-range is missing, thank you. 

I try to look for some other good data-source, if you find some, feel free to paste some links here.

**Comment by ncorona** [comment] 2023-08-28 20:18
@fabiocaccamo ok!  Thanks for your time.

**Comment by fabiocaccamo** [comment] 2023-08-28 21:08
@ncorona looking the original dataset it seems more that the cause of the missing date range are duplicated rows, as you can see the rows are identical except for the dates (I don't think that the municipality has been suppressed in that time frame and then re-created):

```csv
20589,"1861-03-17","1928-11-27","092081","G133","ORTACESUS","ORTACESUS","","",92,"092","20","","C","CA","","2016-06-17",""
20588,"1948-05-07","1974-08-19","092081","G133","ORTACESUS","ORTACESUS","","",92,"092","20","","C","CA","","2016-06-17",""
```

**Comment by ncorona** [comment] 2023-09-05 06:27
@fabiocaccamo that's exactly the problem. It is very likely that there are no data for that time interval and I would like to ask whoever created the dataset the reason for this missing data... but I wouldn't know who to address the request to.

**Comment by fabiocaccamo** [comment] 2023-09-05 07:51
@ncorona I think the only solution is to automatically merge data fetched from from https://www.anagrafenazionale.interno.it/ with a manually-managed json file.

**Comment by fabiocaccamo** [comment] 2023-09-05 20:42
@ncorona in `0.8.1` version the codes you reported are working correctly for the missing date-ranges.

Now the automatically-fetched municipalities data gets merged with the manually-managed patch data present in this file:
https://github.com/fabiocaccamo/python-codicefiscale/blob/main/codicefiscale/data/municipalities-patch.json

So... until a perfect data-source will exist *(I doubt that it will happen)*, the patching mechanism can be a valid workaround.

**Closed by fabiocaccamo** 2023-09-05 20:42 UTC
Labels: bug
